# Generated by Django 2.2.6 on 2019-11-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=5)),
                ('present', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fac_Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=5)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stud_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=5)),
            ],
        ),
    ]
