# Generated by Django 2.2.6 on 2019-11-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='t',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
