# Generated by Django 2.2.6 on 2019-11-08 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_attendence_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='t',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
